name: moarTP
main: com.ofallonminecraft.moarTP.moarTP
version: 0.61

commands:
  whereis:
    description: Find the nearest public location to an online player.
    usage: /whereis [player]
    permission: moarTP.whereis
    permission-message: You should have permission to use this command.
  unclaim:
    description: Remove a location from the system.
    usage: /unclaim [location]
    permission: moarTP.unclaim
    permission-message: You must be an op or the creator of the location to use this command.
  view:
    description: View all locations or locations created by a certain player.
    usage: /view (player)
    permission: moarTP.view
    permission-message: You should have permission to use this command.
  tpto:
    description: Teleport to a location.
    usage: /tpto [location] (password)
    permission: moarTP.tpto
    permission-message: You must be a player to use this command.
  claim:
    description: Claim a new location.
    usage: /claim [location] (["description"])
    permission: moarTP.claim
    permission-message: You must be a player to use this command.
  claimsecret:
    description: Claim a secret location.
    usage: /claimsecret [location] [password] (["description"])
    permission: moarTP.claimsecret
    permission-message: You must be a player to use this command.
  move:
    description: Move a player to a custom location.
    usage: /move [player1(,player2,player3,...)] [location] (password)
    permission: moarTP.move
    permission-message: You must be an op to use this command.
  about:
    description: View location information.
    usage: /about [location]
    permission: moarTP.about
    permission-message: You should be able to use this command.
  sethome:
    description: Set your personal home location.
    usage: /sethome [location]
    permission: moarTP.sethome
    permission-message: You must be a player to use this command.
  gohome:
    description: Go to your personal home location.
    usage: /gohome
    permission: moarTP.gohome
    permission-message: You must be a player to use this command.

permissions:
  moarTP.*:
    description: Gives access to all moarTP commands
    children:
      moarTP.whereis: true
      moarTP.unclaim: true
      moarTP.view: true
      moarTP.tpto: true
      moarTP.claim: true
      moarTP.claimsecret: true
      moarTP.move: true
      moarTP.about: true
      moarTP.sethome: true
      moarTP.gohome: true
  moarTP.whereis:
    description: Find the nearest public location to an online player.
    default: true
  moarTP.unclaim:
    description: Remove a location from the system.
    default: true
  moarTP.view:
    description: View all locations in the system.
    default: true
  moarTP.tpto:
    description: Teleport to a location.
    default: true
  moarTP.claim:
    description: Claim a new location.
    default: true
  moarTP.claimsecret:
    description: Claim a secret location.
    default: true
  moarTP.move:
    description: Move a player to a custom location.
    default: op
  moarTP.about:
    description: View location information.
    default: true
  moarTP.sethome:
    description: Set your personal home location.
    default: true
  moarTP.gohome:
    description: Go to your personal home location.
    default: true